[package]
name = "hexasphere"
version = "3.1.0"
authors = ["OptimisticPeach <patrikbuhring@gmail.com>"]
edition = "2018"
description = """
A library to evenly tile hexagons on a sphere.
"""
readme = "readme.md"
repository = "https://github.com/OptimisticPeach/hexasphere.git"
license = "MPL-2.0"
keywords = ["gamedev", "graphics", "hexagons", "sphere", "math"]
categories = ["algorithms", "data-structures", "graphics", "mathematics", "rendering::data-formats"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
adjacency = ["smallvec"]

[dependencies]
glam = ">= 0.11, <= 0.12"
lazy_static = "1.4"

smallvec = { version = "1.4.2", optional = true }
